services:
  planner-db:
    container_name: planner-db
    image: bitnami/postgresql
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: ${JOURNEY_DATABASE_USER}
      POSTGRESQL_PASSWORD: ${JOURNEY_DATABASE_PASSWORD}
      POSTGRESQL_DATABASE: ${JOURNEY_DATABASE_NAME}
    volumes:
      - db:/var/lib/postgresql/data

  app:
    build: .
    expose:
      - 8080:8080
    depends_on:
      - planner-db

volumes:
  db:
    driver: local
